"use client";

// Stage 4j — PDF export using jsPDF + jspdf-autotable.
//
// Each section becomes a table. Charts are NOT embedded as images —
// per spec, tables are clearer for institutional readers and avoid the
// bundle weight of html2canvas. If chart visuals become a hard
// requirement later, add them in a follow-up stage.

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

import { formatRangeISO } from "./services/dateUtils";

const PAGE_MARGIN = 14;
const safeLabel = (s) => String(s || "report").replace(/[^a-zA-Z0-9-]+/g, "-");

// Footer painted on every page. autoTable triggers didDrawPage for each
// page it adds, but we also paint the title page footer explicitly.
const drawFooter = (doc) => {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
      `GIMPA Smart Resource Management — Page ${i} of ${pageCount}`,
      w / 2,
      h - 8,
      { align: "center" }
    );
  }
};

const drawTitlePage = (doc, { period, user, title }) => {
  const w = doc.internal.pageSize.getWidth();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(30);
  doc.text("GIMPA Smart Resource Management", w / 2, 60, { align: "center" });

  doc.setFontSize(16);
  doc.setTextColor(60);
  doc.text(title || "Operations Report", w / 2, 72, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(40);

  let y = 110;
  const left = PAGE_MARGIN + 6;
  const writeRow = (label, value) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, left, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, left + 50, y);
    y += 8;
  };

  if (period) {
    writeRow("Period:", period.label);
    writeRow(
      "From:",
      `${formatRangeISO(period.startDate)}  to  ${formatRangeISO(period.endDate)}`
    );
  }
  if (user) {
    writeRow("Generated by:", `${user.fullName || user.email || "User"} (${user.role || "—"})`);
  }
  writeRow("Generated on:", new Date().toLocaleString("en-GB"));
};

const drawSectionTable = (doc, section, startY) => {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30);
  doc.text(section.title, PAGE_MARGIN, startY);

  if (section.summary) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(80);
    doc.text(section.summary, PAGE_MARGIN, startY + 6);
  }

  autoTable(doc, {
    startY: startY + (section.summary ? 12 : 8),
    head: [section.columns],
    body: section.rows,
    theme: "striped",
    headStyles: { fillColor: [74, 108, 247], textColor: 255 },
    styles: { fontSize: 10, cellPadding: 4 },
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN }
  });
};

export const exportToPdf = ({ title, sections, period, user, filename }) => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  drawTitlePage(doc, { period, user, title });

  for (const section of sections) {
    if (!section || !section.columns || !section.rows) continue;
    doc.addPage();
    drawSectionTable(doc, section, 24);
  }

  drawFooter(doc);

  const fname = filename
    || `gimpa-report-${safeLabel(period?.label)}-${formatRangeISO(new Date())}.pdf`;

  doc.save(fname);
};
